# Contributor task runner. Every target here wraps a command that CI runs
# (.github/workflows/ci.yml); keep the two in step. Run `make` for the list.

UV ?= uv
UVX ?= uvx
# Dev toolchain, pinned exactly, in one place. `uvx`/`uv run --with` resolve a
# bare name to whatever is newest at the time, so a lint or typecheck run could
# silently change behaviour (or go red) after a tool release; CI and every
# contributor then ran different versions. Bump these deliberately.
RUFF_VERSION := 0.16.9
BLACK_VERSION := 26.5.1
MYPY_VERSION := 2.3.1
YAMLLINT_VERSION := 1.38.0
PYTEST_VERSION := 9.1.1
HYPOTHESIS_VERSION := 6.168.3
PYTEST_COV_VERSION := 7.1.0
# Mirrors the range in python/pyproject.toml so tests run against the same
# cloudpickle the wheel declares.
CLOUDPICKLE_SPEC := 'cloudpickle>=3.1.2,<4'  # quoted: make hands it to /bin/sh

PYTEST_DEPS = --with pytest==$(PYTEST_VERSION) --with hypothesis==$(HYPOTHESIS_VERSION) \
	--with pytest-cov==$(PYTEST_COV_VERSION) --with $(CLOUDPICKLE_SPEC)
PYTEST = $(UV) run $(PYTEST_DEPS) pytest
LINT_PATHS = python examples scripts tests
# Reproducible-builds.org: a fixed epoch (so archives and wheels do not carry the
# build time) plus C collation and UTC for anything that formats or sorts.
# SOURCE_DATE_EPOCH comes from the last commit, so it is stable per tree; the git
# fallback covers a build from an unpacked tarball with no history.
SOURCE_DATE_EPOCH ?= $(shell git log -1 --pretty=%ct 2>/dev/null || echo 0)
export SOURCE_DATE_EPOCH
REPRO_ENV = TZ=UTC LC_ALL=C PYTHONHASHSEED=0

.DEFAULT_GOAL := help
.PHONY: help test test-one e2e lint format types shell yaml import build bundle repro release-check check

help:  ## list targets
	@grep -hE '^[a-z-]+:.*## ' $(MAKEFILE_LIST) | awk -F':.*## ' '{printf "  %-10s %s\n", $$1, $$2}'

test:  ## unit + fuzz suite with the 100% coverage gate (no GPUs needed)
	$(PYTEST) tests/ -q --cov=ray --cov-report=term-missing --cov-fail-under=100

test-one:  ## one test or pattern: make test-one T=tests/test_cli.py::test_x
	$(PYTEST) $(T) -q

e2e:  ## control-plane harnesses: single-node, multi-node, edge, driver-on-worker
	bash test/run_e2e.sh
	bash test/run_multinode.sh
	bash test/run_edge.sh
	bash test/run_driver_on_worker.sh

lint:  ## ruff check + black --check (as CI runs them)
	$(UVX) ruff==$(RUFF_VERSION) check $(LINT_PATHS)
	$(UVX) black==$(BLACK_VERSION) --check $(LINT_PATHS)

format:  ## rewrite with black
	$(UVX) black==$(BLACK_VERSION) $(LINT_PATHS)

types:  ## mypy strict over python/ray
	$(UVX) --with $(CLOUDPICKLE_SPEC) mypy==$(MYPY_VERSION) --config-file pyproject.toml python/ray

shell:  ## shellcheck the harnesses
	shellcheck -x test/*.sh test/dgx/*.sh

yaml:  ## yamllint the CI workflows
	$(UVX) yamllint==$(YAMLLINT_VERSION) -c .yamllint.yml .github/workflows/ci.yml .github/workflows/release.yml

release-check:  ## version numbers, docs and CHANGELOG agree (add TAG=v0.3.0 to check a cut)
	python3 scripts/check_release.py $(if $(TAG),--tag $(TAG),)

import:  ## import-only smoke test of the whole shim surface
	PYTHONPATH=python $(UV) run --with $(CLOUDPICKLE_SPEC) python examples/import_check.py

sbom:  ## CycloneDX inventory of the resolved dependency tree
	$(UV) export --format cyclonedx1.5 --no-header -o python/dist/beam-sbom.cdx.json

lockfile-export:  ## refresh requirements.lock (the harness install list, hashed)
	@# uv writes the header it was given, so `--no-header` here and the file's
	@# own purpose below; `--no-emit-project` keeps the `-e ./python` line out,
	@# since the harnesses run the shim from PYTHONPATH, not from site-packages.
	$(UV) export --format requirements.txt --no-header --no-emit-package ray \
		-o requirements.lock.tmp
	@{ \
	  printf '%s\n' \
	    '# Generated by `make lockfile-export` from uv.lock. Hash-pinned install' \
	    '# list for the harnesses (test/lib.sh:beam_install_dep) and for anything' \
	    '# installing into a container that already has the shim on PYTHONPATH;' \
	    '# `uv pip install --no-deps --require-hashes -r requirements.lock`' \
	    '# verifies every artifact.'; \
	  cat requirements.lock.tmp; \
	} > requirements.lock
	@rm -f requirements.lock.tmp

build:  ## wheel + sdist from python/, same command the release workflow runs
	cd python && $(UV) build --out-dir dist

# The bind-mount payload, byte-for-byte what .github/workflows/release.yml makes:
# sorted entries, 0:0 owners, mtimes clamped to SOURCE_DATE_EPOCH, no atime/ctime
# in the pax headers. gzip over a pipe stamps no filename and no time of its own,
# so the .gz is deterministic too.
BUNDLE = tar --sort=name --numeric-owner --owner=0 --group=0 \
          --mtime="@$$SOURCE_DATE_EPOCH" --pax-option=delete=atime,delete=ctime \
          --format=posix --exclude=*/dist --exclude=__pycache__ \
          -czf $(1) python examples

bundle:  ## the bind-mount tarball the release publishes
	$(REPRO_ENV) sh -c '$(call BUNDLE,beam-bindmount.tar.gz)'

repro:  ## build the artifacts twice, perturb the inputs, and require identical bytes
	@set -eu; \
	rm -rf .repro-a .repro-b; \
	mkdir -p .repro-a/python .repro-b/python; \
	cp -r python/. .repro-a/python/; cp -r python/. .repro-b/python/; \
	cp -r examples .repro-a/; cp -r examples .repro-b/; \
	find .repro-a .repro-b -name __pycache__ -type d -prune -exec rm -rf {} +; \
	find .repro-b -type f -exec touch -t 201905050505 {} +; \
	(cd .repro-a/python && $(REPRO_ENV) $(UV) build --out-dir ../dist >/dev/null); \
	(cd .repro-b/python && $(REPRO_ENV) $(UV) build --out-dir ../dist >/dev/null); \
	(cd .repro-a && $(REPRO_ENV) sh -c '$(call BUNDLE,beam-repro-a.tar.gz)'); \
	(cd .repro-b && $(REPRO_ENV) sh -c '$(call BUNDLE,beam-repro-b.tar.gz)'); \
	cmp .repro-a/beam-repro-a.tar.gz .repro-b/beam-repro-b.tar.gz && echo 'reproducible: bundle'; \
	cmp .repro-a/dist/*.whl .repro-b/dist/*.whl && echo 'reproducible: wheel'; \
	cmp .repro-a/dist/*.tar.gz .repro-b/dist/*.tar.gz && echo 'reproducible: sdist'; \
	rm -rf .repro-a .repro-b

check: lint types shell yaml test import release-check e2e  ## everything CI runs
